# Generated by Django 3.0 on 2020-05-23 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeprofile',
            name='code_inputs',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='codeprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
