# Generated by Django 3.0 on 2020-05-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kode', '0002_auto_20200523_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeprofile',
            name='code_inputs',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='codeprofile',
            name='code_outputs',
            field=models.TextField(null=True),
        ),
    ]
