# Generated by Django 3.0 on 2020-05-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kode', '0003_auto_20200523_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeprofile',
            name='code_inputs',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='codeprofile',
            name='code_outputs',
            field=models.TextField(default='None'),
        ),
    ]
