# Generated by Django 3.0 on 2020-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kode', '0004_auto_20200523_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeprofile',
            name='code_points',
            field=models.IntegerField(default=0),
        ),
    ]
